defaults:
  - experiment: exp2_compute_matched_utility_central
  - hp_candidate_set: mnist_learning_rate
  - _self_

paths:
  results_root: results_central

hydra:
  run:
    dir: ${paths.results_root}/${experiment.name}/${experiment.run_id}
  job:
    chdir: false

run_settings:
  rounds: 2000 # Needs to match stage 1 or stage 2 end
  weight_decay: 0
  use_cuda: true
  dp: true
  sampling_rate: 0.002
  noise_multiplier: 5.0
  max_grad_norm: 1.0
  data_sampling_scheme: "poisson_sampling"
  optimizer_name: "SGD"
  momentum: 0.0
  checkpoint_interval: 100
  evaluation_interval: 100
