defaults:
  - dataset: synthetic
  - _self_

hydra:
  run:
    dir: dump

run_mode:
  find_optimum: False
  tune_hyperparameter: True
  compile_tuning_results: False
  simulate: False
  compile_results: False

run_settings:
  rounds: 150
  algorithm: FedAvg
  seed: 0
  use_cuda: True
  visualize_data_partition: False
  resume_from_checkpoint: False

tuning:
  parameter_to_tune: clipping
  type: early_stopping
  early_stopping_resource: rounds
  min_resource: 10
  elimination_rate: 2
  cv_folds: 1
  hyperparameter_grid: [0.5]
  save_path: tuning_results/${server.sampling_scheme}/${run_settings.algorithm}/${dataset.name}/${dataset.model_name}_${run_settings.rounds}T_${server.local_updates}K_${server.sampling_rate}sr_${server.dp}dp
  metric: train_loss

server:
  constant_global_step: Heuristic
  sampling_scheme: poisson_sampling
  global_step: 
  local_step: 2.56
  client_ratio: 0.02
  local_updates: 50
  weight_decay: 0.0
  sampling_rate: 0.2
  dp: True
  sigma: 5.0
  max_grad_norm: 

results:
  client_ratio_vs_beta: True
  transfer_mode: client_ratio
  transfer_parameters: [0.1,0.13,0.15,0.17,0.21]
  result_path: results/${run_settings.algorithm}/${dataset.name}/${dataset.model_name}

  # [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
  # [0.04, 0.08, 0.16, 0.32, 0.64, 1.28, 2.56, 5.12]