defaults:
  - experiment: exp1_compute_matched_utility
  - dataset: synthetic
  - hp_candidate_set: synthetic_learning_rate
  - _self_

paths:
  results_root: results

hydra:
  run:
    dir: ${paths.results_root}/${experiment.name}/${experiment.run_id}
  job:
    chdir: false

run_mode:
  find_optimum: False
  tune_hyperparameter: False
  compile_tuning_results: False
  simulate: False
  compile_results: False

run_settings:
  rounds: 150
  algorithm: FedAvg
  seed: 0
  use_cuda: True
  visualize_data_partition: False
  resume_from_checkpoint: False

tuning:
  parameter_to_tune: 
  type: 
  early_stopping_resource: 
  min_resource: 
  elimination_rate: 
  cv_folds: 
  hyperparameter_grid: 
  save_path: 
  metric: 

server:
  constant_global_step: Adaptive
  client_sampling_scheme: poisson_sampling
  data_sampling_scheme: fixed_size_sampling
  global_step: 
  local_step: 
  client_ratio: 0.21
  local_updates: 6
  weight_decay: 0.0
  sampling_rate: 0.2
  dp: True
  sigma: 20.0
  max_grad_norm: 2.0

results:
  client_ratio_vs_beta: 
  transfer_mode: 
  transfer_parameters: 
  result_path: 

  # [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
  # [0.04, 0.08, 0.16, 0.32, 0.64, 1.28, 2.56, 5.12]
